id: P4D49B116
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1KG1104
  instance_id: http://purl.bdrc.io/resource/IE1KG1104
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - རྩ་རྒྱུད་འགྲེལ་པ་ཕྱོགས་བསྒྲིགས།
  alt_title:
    zh-latn-pinyin-x-ndia:
    - gen ben bu yi dian zhu shi hui bian
  author: http://purl.bdrc.io/resource/P4113
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    a386ebf4cb054cd78a2216ff9809b044:
      title: པོད ༡་རྩ་རྒྱུད་འགྲེལ་པ་ཕྱོགས་བསྒྲིགས
      volume_number: 1
      base_file: UT1KG1104_I1KG2735_0000.txt
      reference: http://purl.bdrc.io/resource/VL74E7730785549B99
      image_group: I1KG2735
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/W1KG1104
  - http://purl.bdrc.io/resource/MW1KG1104
  ocr_software: Namsel
created_at: '2021-12-22T10:30:43.702592'
last_modified_at: '2021-12-22T10:30:43.702599'
